# numpy =>> ons channel

In [1]:
import numpy as np

In [2]:
# array  # arange  # zeros  #ones # random.random  #random.randint  # random.normal  #full

In [4]:
n=np.array([1,2,3,4,5])
n

array([1, 2, 3, 4, 5])

In [5]:
print(n[0])
print(n[2])
print(n[-1])

1
3
5


In [6]:
m=np.array([3.5,4,2])
m

array([3.5, 4. , 2. ])

In [7]:
n=np.array([1,2,3,4,5] , dtype='float32')
n

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
## np.ones((3, 6) ,dtype=int)

In [10]:
np.full((2,4) , 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [11]:
np.arange(2 , 18, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.random.random((3,3))

array([[0.8529147 , 0.3646214 , 0.39896242],
       [0.41167302, 0.3977531 , 0.27255392],
       [0.43155715, 0.17692309, 0.95008818]])

In [14]:
np.random.randint( 0 ,10 ,(3,3))

array([[1, 1, 0],
       [1, 8, 1],
       [0, 6, 6]])

In [15]:
np.random.normal( 0 ,1 ,(3,3))

array([[ 1.95797217, -0.99762122, -0.04031   ],
       [-0.0085281 , -0.93458095,  1.38014066],
       [-1.13490958, -1.00030617, -0.60577324]])

In [16]:
np.eye(7  , dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [17]:
np.empty((3 ,3))

array([[1.95797217, 0.99762122, 0.04031   ],
       [0.0085281 , 0.93458095, 1.38014066],
       [1.13490958, 1.00030617, 0.60577324]])

In [18]:
x=np.zeros((3,4 ,5))
x   

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
print(x.ndim)
print(x.size)
print(x.shape)

3
60
(3, 4, 5)


In [20]:
z= np.array([[1,2,3,4],[5,6,7,8],[1,4,7,8]])
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 4, 7, 8]])

In [21]:
z[0,0]

1

In [22]:
z[2,1]

4

In [23]:
z[0,0]=3
z

array([[3, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 4, 7, 8]])

In [24]:
c=np.arange(1,20)
print(c)
print(c[:2])
print(c[:9])
print(c[3:])
print(c[3:-1])
print(c[:6])
print(c[2:6])
print(c[::2])
print(c[1::2])
print(c[::-1])
print(c[::-2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]
[1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[1 2 3 4 5 6]
[3 4 5 6]
[ 1  3  5  7  9 11 13 15 17 19]
[ 2  4  6  8 10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[19 17 15 13 11  9  7  5  3  1]


In [25]:
y= np.array([[1,2,3,4 ,5],[5,6,7,8 ,9],[1,4,7,8,2]])
print(y)
print('.'*50)
print(y[0:2 ,2 :3])
print('.'*50)
print(y[1 ,1 :3])
print('.'*50)
print(y[:2 , :3])
print('.'*50)
print(y[:2 , ::2])
print('.'*50)
print(y[1: , 3:])
print('.'*50)
print(y[:2 , ::-1])
print('.'*50)
print(y[: , 0])
print('.'*50)
print(y[0 , :])

[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 4 7 8 2]]
..................................................
[[3]
 [7]]
..................................................
[6 7]
..................................................
[[1 2 3]
 [5 6 7]]
..................................................
[[1 3 5]
 [5 7 9]]
..................................................
[[8 9]
 [8 2]]
..................................................
[[5 4 3 2 1]
 [9 8 7 6 5]]
..................................................
[1 5 1]
..................................................
[1 2 3 4 5]


In [26]:
y=np.arange(1 ,10).reshape((3 , 3))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
x= np.array([1,2,3 ])
x.reshape((1,3))

array([[1, 2, 3]])

In [28]:
x.reshape((3,1 ))

array([[1],
       [2],
       [3]])

In [29]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.array([1,4,7,5])
np.concatenate((x,y ,z))

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 4, 7, 5])

In [30]:
a=np.full((2,3),1)
b=np.full((2,3),9)
np.concatenate([a,b] , axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [31]:
a=np.full((2,3),1)
b=np.full((2,3),9)
np.concatenate([a,b] , axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [32]:
a= np.full((2,3),1)
b=np.full((2,3),9)
np.vstack([a,b] )

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [33]:
a=np.full((2,3),1)
b=np.full((2,3),9)
np.hstack([a,b] )

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [34]:
x=[1,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(x , [3,6])
print(x1 ,x2 ,x3)

[1 2 3] [4 5 6] [7 8 9]


In [35]:
grid=np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
upper , lower =np.vsplit(grid , [3])
print(upper)
print()
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [36]:
big_array = np.random.randint(1 ,100 , size=10000)
%time 1. /big_array

Wall time: 53.1 ms


array([0.02564103, 0.01136364, 0.08333333, ..., 0.01010101, 0.025     ,
       0.01315789])

In [37]:
x= np.arange(9).reshape(3,3)
x**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [38]:
x= np.arange(5)
print("x" , x)
print("x+5=" , x+5)
print("x-5=" , x-5)
print("x/5=" , x/5)
print("x+5=" , x+5)
print("x*5=" , x*5)

x [0 1 2 3 4]
x+5= [5 6 7 8 9]
x-5= [-5 -4 -3 -2 -1]
x/5= [0.  0.2 0.4 0.6 0.8]
x+5= [5 6 7 8 9]
x*5= [ 0  5 10 15 20]


In [39]:
theta= np.linspace(0 ,np.pi ,3)
theta
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [112]:
x=[-1,0,1]
theta= np.linspace(0 ,np.pi ,3)
theta
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [40]:
x=[1,2,3,4,5]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [44]:
z=np.random.random(100)
sum(z)

44.99967134993864

In [118]:
c= np.arange(0,10)
print(c.sum())
print(c.min())
print(c.max())

45
0
9


In [45]:
v=np.arange(0,9).reshape(3,3)
v
print(v.sum(axis=0))
print(v.sum(axis=1))

[ 9 12 15]
[ 3 12 21]


In [46]:
v=np.arange(0,9).reshape(3,3)
print(np.percentile(v ,25))
print(np.percentile(v ,50))
print(np.percentile(v ,75))


2.0
4.0
6.0


# project

In [129]:
import pandas as pd


In [130]:
df=pd.read_csv('company_sales_data.csv')

In [133]:
df.head()

month_number  facecream  facewash  toothpaste  bathingsoap  shampoo  \
0             1       2500      1500        5200         9200     1200   
1             2       2630      1200        5100         6100     2100   
2             3       2140      1340        4550         9550     3550   
3             4       3400      1130        5870         8870     1870   
4             5       3600      1740        4560         7760     1560   

   moisturizer  total_units  total_profit  
0         1500        21100        211000  
1         1200        18330        183300  
2         1340        22470        224700  
3         1130        22270        222700  
4         1740        20960        209600

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month_number  12 non-null     int64
 1   facecream     12 non-null     int64
 2   facewash      12 non-null     int64
 3   toothpaste    12 non-null     int64
 4   bathingsoap   12 non-null     int64
 5   shampoo       12 non-null     int64
 6   moisturizer   12 non-null     int64
 7   total_units   12 non-null     int64
 8   total_profit  12 non-null     int64
dtypes: int64(9)
memory usage: 992.0 bytes


In [170]:
data =df.iloc[:-3: ].values
data

array([[     1,   2500,   1500,   5200,   9200,   1200,   1500,  21100,
        211000],
       [     2,   2630,   1200,   5100,   6100,   2100,   1200,  18330,
        183300],
       [     3,   2140,   1340,   4550,   9550,   3550,   1340,  22470,
        224700],
       [     4,   3400,   1130,   5870,   8870,   1870,   1130,  22270,
        222700],
       [     5,   3600,   1740,   4560,   7760,   1560,   1740,  20960,
        209600],
       [     6,   2760,   1555,   4890,   7490,   1890,   1555,  20140,
        201400],
       [     7,   2980,   1120,   4780,   8980,   1780,   1120,  29550,
        295500],
       [     8,   3700,   1400,   5860,   9960,   2860,   1400,  36140,
        361400],
       [     9,   3540,   1780,   6100,   8100,   2100,   1780,  23400,
        234000]], dtype=int64)

In [141]:
data =df.iloc[:4 ,: 2].values
data

array([[   1, 2500],
       [   2, 2630],
       [   3, 2140],
       [   4, 3400]], dtype=int64)

In [145]:
print(df.ndim)
print(df.size)
print(df.shape)

2
108
(12, 9)


In [147]:
data.dtype

dtype('int64')

In [171]:
data[: ,:]

array([[     1,   2500,   1500,   5200,   9200,   1200,   1500,  21100,
        211000],
       [     2,   2630,   1200,   5100,   6100,   2100,   1200,  18330,
        183300],
       [     3,   2140,   1340,   4550,   9550,   3550,   1340,  22470,
        224700],
       [     4,   3400,   1130,   5870,   8870,   1870,   1130,  22270,
        222700],
       [     5,   3600,   1740,   4560,   7760,   1560,   1740,  20960,
        209600],
       [     6,   2760,   1555,   4890,   7490,   1890,   1555,  20140,
        201400],
       [     7,   2980,   1120,   4780,   8980,   1780,   1120,  29550,
        295500],
       [     8,   3700,   1400,   5860,   9960,   2860,   1400,  36140,
        361400],
       [     9,   3540,   1780,   6100,   8100,   2100,   1780,  23400,
        234000]], dtype=int64)

In [173]:
data[:5,:9]

array([[     1,   2500,   1500,   5200,   9200,   1200,   1500,  21100,
        211000],
       [     2,   2630,   1200,   5100,   6100,   2100,   1200,  18330,
        183300],
       [     3,   2140,   1340,   4550,   9550,   3550,   1340,  22470,
        224700],
       [     4,   3400,   1130,   5870,   8870,   1870,   1130,  22270,
        222700],
       [     5,   3600,   1740,   4560,   7760,   1560,   1740,  20960,
        209600]], dtype=int64)

In [176]:
data[::3,:]

array([[     1,   2500,   1500,   5200,   9200,   1200,   1500,  21100,
        211000],
       [     4,   3400,   1130,   5870,   8870,   1870,   1130,  22270,
        222700],
       [     7,   2980,   1120,   4780,   8980,   1780,   1120,  29550,
        295500]], dtype=int64)

In [178]:
total_profit= data[: ,8:9]
total_profit

array([[211000],
       [183300],
       [224700],
       [222700],
       [209600],
       [201400],
       [295500],
       [361400],
       [234000]], dtype=int64)

In [185]:
print(np.max(total_profit))
print(np.min(total_profit))
print(np.mean(total_profit))
print(np.std(total_profit))
print(np.percentile(total_profit ,[25,50 ,75]))
print(np.argmax(total_profit))

361400
183300
238177.77777777778
52522.70996177173
[209600. 222700. 234000.]
7


In [187]:
print('-'*120)

------------------------------------------------------------------------------------------------------------------------


In [188]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [189]:
np.array(my_list)

array([1, 2, 3])

In [190]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [191]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
list(range(0, 11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [193]:
list(range(0, 11, 2))

[0, 2, 4, 6, 8, 10]

In [194]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [196]:
np.zeros(3)

array([0., 0., 0.])

In [197]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [198]:
np.ones(3)

array([1., 1., 1.])

In [199]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [200]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [201]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [202]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [203]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [204]:
np.random.rand(3)

array([0.65164294, 0.81814192, 0.46226479])

In [205]:
np.random.rand(5, 5)

array([[0.74631994, 0.34193635, 0.66370257, 0.89428189, 0.1380749 ],
       [0.93739436, 0.93597351, 0.79854358, 0.90443574, 0.36844778],
       [0.6121682 , 0.43241472, 0.17612514, 0.5398941 , 0.95677255],
       [0.26454232, 0.70780105, 0.69080716, 0.94507233, 0.16462565],
       [0.14859177, 0.06121016, 0.64875182, 0.60166929, 0.69684407]])

In [206]:
np.random.randn(2)

array([-0.1579929 , -1.53303364])

In [207]:
np.random.randint(1, 100)

34

In [208]:
np.random.randint(1, 100, 10)

array([ 1, 56,  5, 62, 66,  9, 75, 25, 55, 60])

In [209]:
np.random.randint(1, 100, (5, 5))

array([[36, 23, 71, 11, 29],
       [99, 66, 31, 47, 40],
       [46,  9, 79, 56, 85],
       [74, 58, 32, 60, 81],
       [49, 42, 96,  4, 46]])

In [210]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 7, 16, 35, 42,  1, 45, 27, 28, 16, 19])

In [211]:
ranarr.max()

45

In [212]:
ranarr.argmax()

5

In [213]:
ranarr.min()

1

In [214]:
ranarr.argmin()

4

In [215]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
linarr = np.linspace(0,2,11)

In [216]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [217]:
arr.shape

(25,)

In [218]:
ranarr

array([44, 12, 46,  0, 42,  3, 22,  8,  5, 11])

In [219]:
ranarr.shape

(10,)

In [220]:
linarr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [221]:
linarr.shape

(11,)

In [222]:
reshaped = arr.reshape(5, 5)
reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [223]:
reshaped.shape

(5, 5)

In [224]:
reshaped.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [225]:
reshaped.reshape(25).shape

(25,)

In [226]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [227]:
arr.reshape(1, 25).shape

(1, 25)

In [228]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)
b

In [ ]:
arr = np.arange(5)
arr

In [ ]:
arr = np.arange(0,11,2)
arr

In [ ]:
arr = np.zeros((2,3))
arr

In [ ]:
arr = np.ones((4,5))
arr

In [ ]:
arr = np.linspace(1,2,9)
arr

In [ ]:
arr = np.random.randint(20,50,10)
arr

In [ ]:
np.insert(a,1,5)
a

In [ ]:
np.delete(a,1)


In [ ]:
b.reshape(3,2)
b

In [ ]:
np.append(a,b)

In [ ]:
np.add(b,a)

In [ ]:
np.subtract(b,a)

In [ ]:
np.multiply(a,b)

In [ ]:
np.sqrt(b)

In [ ]:
np.sin(b)

In [ ]:
np.log(b)

In [ ]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

c = a + b
d = a * b

print(c)
print("\n",d)

In [ ]:
import numpy as np

a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

o = a.astype('int')

print(o)

In [ ]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

In [ ]:
import numpy

sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[:,-1]
print(newArray)

In [ ]:
import numpy

firstArray = numpy.empty([5,3], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("\nPrinting numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

In [ ]:
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
newArray = sampleArray[::2, 1::2]
print(newArray)

In [ ]:
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

resultArray = [num ** 2 for num in resultArray]

resultArray = numpy.array([resultArray[0],resultArray[1]])
resultArray

print("\nResult array after calculating the square root of all elements\n")

In [ ]:
ar = np.arange(1,21)
ar

In [ ]:
ar = np.arange(1.5,21.3,.2)
ar

In [ ]:
ar = range(1.5,21.3,.2)
ar

In [ ]:
arr = np.array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])
arr

In [ ]:
arr = np.arange(10,22)
arr.reshape(3,4)

In [ ]:
X = np.array([1, 7, 13, 105])
X.sum()

In [ ]:
arr = np.array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])
arr.sum()

In [ ]:
arr = np.array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])
arr.sum()

In [ ]:
np.isnan(a).sum()

In [ ]:
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

In [ ]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

In [ ]:
x = np.arange(12, 38)
print(x.size)
print(x.shape)

In [ ]:
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

In [ ]:
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)

In [ ]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

In [ ]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

In [ ]:
a = np.arange(4).reshape((2,2))
print("Original flattened array:")
print(a)
print("Maximum value of the above flattened array:")
print(np.amax(a))
print("Minimum value of the above flattened array:")
print(np.amin(a))

In [ ]:
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5]) # rounds to nearest even value
print(x)


In [ ]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

In [ ]:
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

In [ ]:
x = np.array([1, np.e, np.e**2])
print("Original array: ")
print(x)
print("\nNatural log =", np.log(x))
print("Common log =", np.log10(x))
print("Base 2 log =", np.log2(x))

In [ ]:
import numpy as np
import time
import gc # garbage collection
import sys


def compare_times(f1, f2, setup1=None, setup2=None, runs=30):
    print('    format: mean seconds (standard error)', runs, 'runs')
    maxpad = max(len(f.__name__) for f in (f1, f2))
    means = []
    for setup, f in [[setup1, f1], [setup2, f2]]:
        setup = (lambda: tuple()) if setup is None else setup
        
        total_times = []
        for _ in range(runs):
            try:
                gc.disable()
                args = setup()
                
                start = time.time()
                if isinstance(args, tuple):
                    f(*args)
                else:
                    f(args)
                end = time.time()
                
                total_times.append(end - start)
            finally:
                gc.enable()
                
        mean = np.mean(total_times)
        se = np.std(total_times) / np.sqrt(len(total_times))
        print('    {} {:.2e} ({:.2e})'.format(f.__name__.ljust(maxpad), mean, se))
        means.append(mean)
    print('    improvement ratio {:.1f}'.format(means[0] / means[1]))

In [ ]:
size = 10 ** 7 
print('create a list 1, 2, ...', size)


def create_list(): return list(range(size))
def create_array(): return np.arange(size, dtype=int)

compare_times(create_list, create_array)

In [ ]:
import time
num = 10000000
a = np.random.random(num)
b = np.random.random(num)

star = time.time()
c = np.dot(a,b)
en = time.time()
print(c)
print("Verctorize  : " +  str((en -star)*1000) + 'ms')

d =0
start = time.time()
for i in range(num):
    d += a[i]*b[i]
end = time.time()

print(d)
print("Loop version  : " +  str((end -start)*1000) + 'ms')
print("Vectorization is faster by" , (end -start)/(en -star) , 'times')

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

In [ ]:
arr_2d[1]

In [ ]:
arr_2d[1][0]

In [ ]:
arr_2d[1, 0]

In [ ]:
arr_2d

In [ ]:
arr_2d[:2,1:]

In [ ]:
arr_2d[2]

In [ ]:
arr_2d[2,:]

In [ ]:
arr_2d

In [ ]:
arr_2d[::-1,::]

In [ ]:
arr_2d[:,::-1]

In [ ]:
arr_2d[::-1,::-1]

In [ ]:
#Set up matrix
arr2d = np.random.randint(1, 100, (10,10))
arr2d

In [ ]:
arr2d[[1,4,6,8]]

In [ ]:
arr2d[[6,4,2,7]]

In [ ]:
arr2d[[1,4,6,8], 2:5]

In [ ]:

arr = np.arange(0,10)
arr

In [ ]:
arr + 3

In [ ]:
arr * 2

In [ ]:
arr - 10

In [ ]:
arr + arr

In [ ]:
arr - arr

In [ ]:
arr / arr

In [ ]:
arr ** 3

In [ ]:
arr > 3

In [ ]:
arr != 3

In [ ]:
arr = np.random.randint(0,10, (3,3))
arr

In [ ]:
arr + 3

In [ ]:
arr - 2

In [ ]:
3 * arr

In [ ]:
arr + 3 * arr

In [ ]:
arr * arr

In [ ]:
arr = np.arange(0,10)
arr

In [ ]:
matrix = np.random.randint(0, 100, (5, 3))
matrix

In [ ]:
np.max(arr) #same as arr.max()

In [ ]:
np.max(matrix, axis=0)

In [ ]:
np.max(matrix, axis=1)

In [ ]:
np.min(matrix, axis=0)

In [ ]:
np.min(matrix, axis=1)

In [ ]:
np.average(arr)

In [ ]:
np.average(matrix)

In [ ]:
np.average(matrix, axis=0)

In [ ]:
np.average(matrix, axis=1)

In [ ]:
np.average(matrix, axis=1)

In [ ]:
np.sum(arr)

In [ ]:
np.sum(matrix)

In [ ]:
np.sum(matrix, axis=0)

In [ ]:
np.sum(matrix, axis=1)

In [ ]:
np.power(arr, 3)

In [ ]:
np.power(matrix, 3)

In [ ]:
np.sqrt(arr)

In [ ]:
np.sqrt(matrix)

In [ ]:
np.exp(arr)

In [ ]:
np.exp(matrix)

In [ ]:
np.log(arr)

In [ ]:
np.log(matrix)

In [ ]:
angels_arr = np.linspace(0, 360, 9).reshape(3, 3)
angels_arr

In [ ]:
angels_arr = (angels_arr * 2 * np.pi) / 360
angels_arr

In [ ]:
np.sin(angels_arr)

In [ ]:
np.cos(angels_arr)

In [ ]:
np.tan(angels_arr)

In [ ]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])

print(mat)
print()
print(vec1)
print()
print(np.dot(vec1, mat))

In [ ]:
vec1.dot(mat)