# " Numpy "

In [1]:
import numpy as np

### creating numpy array

In [2]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr=[[1,2,3],[4,5,6],[7,8,9]]
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **Built-in Methods

In [6]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
list(range(0,13,2))

[0, 2, 4, 6, 8, 10, 12]

### 1-arange

In [10]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

### 2-zeros, ones and eye

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### linspace

In [22]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [23]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [24]:
np.linspace(0,15,40)

array([ 0.        ,  0.38461538,  0.76923077,  1.15384615,  1.53846154,
        1.92307692,  2.30769231,  2.69230769,  3.07692308,  3.46153846,
        3.84615385,  4.23076923,  4.61538462,  5.        ,  5.38461538,
        5.76923077,  6.15384615,  6.53846154,  6.92307692,  7.30769231,
        7.69230769,  8.07692308,  8.46153846,  8.84615385,  9.23076923,
        9.61538462, 10.        , 10.38461538, 10.76923077, 11.15384615,
       11.53846154, 11.92307692, 12.30769231, 12.69230769, 13.07692308,
       13.46153846, 13.84615385, 14.23076923, 14.61538462, 15.        ])

### **rand, randn, randint

In [25]:
np.random.rand(3)

array([0.85494176, 0.86237584, 0.61227153])

In [28]:
np.random.rand(3,3)

array([[0.05011138, 0.32996623, 0.64415354],
       [0.84266609, 0.01679079, 0.05940277],
       [0.68009871, 0.85731589, 0.26426777]])

In [30]:
np.random.randn(5)

array([ 0.69927481, -0.84712579, -0.62361691, -0.91993297, -0.73102617])

In [31]:
np.random.randn(5,5)

array([[-0.90862895,  1.38066461, -1.41515035, -0.66746515, -0.74245771],
       [-0.37373114,  1.02592404,  0.53679585, -0.57577852,  0.3950999 ],
       [-1.11075981,  0.10873227,  0.17503197,  0.7651185 ,  0.88204986],
       [ 1.62372027, -2.39383508, -1.57068262,  0.91557048,  0.20700065],
       [-0.64078817, -1.11761289,  0.00529258, -0.20947634,  0.05758242]])

In [35]:
np.random.randint(0,10)

4

In [36]:
np.random.randint(0,10,3)

array([2, 2, 4])

In [39]:
np.random.randint(1,20,(4,4))

array([[ 6,  6,  7, 14],
       [15,  6,  3,  1],
       [ 1, 17, 16, 14],
       [12,  4, 17,  9]])

### **max, min, argmax, argmin

In [41]:
aa=np.random.randint(1,40,8)
aa

array([30, 26, 21, 30, 34, 11, 15, 11])

In [42]:
aa.max()

34

In [43]:
aa.argmax()

4

In [44]:
aa.min()

11

In [45]:
aa.argmin()

5

### **Reshape

In [55]:
arr=np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
arr.shape

(16,)

In [57]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
b=np.random.randint(0,16,12)
b

array([ 9,  7, 13,  6, 15,  9,  4,  5, 13,  6, 12,  0])

In [60]:
b.shape

(12,)

In [61]:
b.reshape(4,3)

array([[ 9,  7, 13],
       [ 6, 15,  9],
       [ 4,  5, 13],
       [ 6, 12,  0]])

In [62]:
b.reshape(3,4)

array([[ 9,  7, 13,  6],
       [15,  9,  4,  5],
       [13,  6, 12,  0]])

In [63]:
b.reshape(2,6)

array([[ 9,  7, 13,  6, 15,  9],
       [ 4,  5, 13,  6, 12,  0]])

### **NumPy Indexing and Selection

In [70]:
z=np.arange(8,25)
z

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
z[4]

12

In [72]:
z[1]

9

In [74]:
z[5:12]

array([13, 14, 15, 16, 17, 18, 19])

In [75]:
z[1:10:2]

array([ 9, 11, 13, 15, 17])

In [76]:
z[:6]

array([ 8,  9, 10, 11, 12, 13])

In [77]:
z[5:]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
arr=np.array([[5,6,9,8],[5,9,8,7],[5,9,6,8]])
arr

array([[5, 6, 9, 8],
       [5, 9, 8, 7],
       [5, 9, 6, 8]])

In [80]:
arr[1]

array([5, 9, 8, 7])

In [81]:
arr[0][1]

6

In [85]:
arr[1:]

array([[5, 9, 8, 7],
       [5, 9, 6, 8]])

In [86]:
arr[2,1]

9

In [88]:
arr[0:2,1:3]

array([[6, 9],
       [9, 8]])

In [89]:
arr[::-1,::]

array([[5, 9, 6, 8],
       [5, 9, 8, 7],
       [5, 6, 9, 8]])

In [92]:
c=np.random.randint(1,100,(10,10))
c

array([[14,  5, 18, 11, 71, 88, 86, 22,  5, 83],
       [39, 98, 47, 51, 23, 22, 60, 54, 81, 83],
       [72, 70,  2,  5, 76, 71, 78, 91, 74,  5],
       [34, 27, 31, 54, 68, 85, 20, 96, 62, 19],
       [51, 78, 21, 43, 86, 81,  5, 60,  8,  2],
       [16, 75, 63, 78, 49, 45, 84, 97, 38, 23],
       [84, 67,  7,  9, 60, 16, 31, 14, 99, 35],
       [18, 61, 83, 71, 61, 22, 77, 59, 63, 55],
       [65, 91, 98, 46, 35, 87, 62, 87, 59, 52],
       [66,  2, 79, 18, 99, 30, 76, 10,  2, 14]])

In [94]:
c[[1,4,5,7]]

array([[39, 98, 47, 51, 23, 22, 60, 54, 81, 83],
       [51, 78, 21, 43, 86, 81,  5, 60,  8,  2],
       [16, 75, 63, 78, 49, 45, 84, 97, 38, 23],
       [18, 61, 83, 71, 61, 22, 77, 59, 63, 55]])

In [96]:
c[[2,4,6,8],2:4]

array([[ 2,  5],
       [21, 43],
       [ 7,  9],
       [98, 46]])

### **Arithmetic and Logic

### 1-Arithmetic

In [126]:
a=np.random.randint(0,10,(5,2))
a

array([[6, 0],
       [0, 8],
       [0, 9],
       [2, 7],
       [7, 7]])

In [128]:
b=a*5
b

array([[30,  0],
       [ 0, 40],
       [ 0, 45],
       [10, 35],
       [35, 35]])

In [129]:
a*5

array([[30,  0],
       [ 0, 40],
       [ 0, 45],
       [10, 35],
       [35, 35]])

In [130]:
a+5

array([[11,  5],
       [ 5, 13],
       [ 5, 14],
       [ 7, 12],
       [12, 12]])

In [131]:
a-10

array([[ -4, -10],
       [-10,  -2],
       [-10,  -1],
       [ -8,  -3],
       [ -3,  -3]])

In [132]:
a-a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [133]:
a/a

C:\Users\Pc\AppData\Local\Temp\ipykernel_15100\2959643021.py:1: RuntimeWarning: invalid value encountered in divide
  a/a


array([[ 1., nan],
       [nan,  1.],
       [nan,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [134]:
a**3

array([[216,   0],
       [  0, 512],
       [  0, 729],
       [  8, 343],
       [343, 343]], dtype=int32)

### 2-logic

In [135]:
ss=np.random.randint(1,100,(10,9))
ss

array([[39, 64, 52, 64,  5, 73,  5, 11,  3],
       [83, 34, 21, 89, 76, 13, 43, 25, 84],
       [78, 36, 15, 41, 88, 53, 93, 78, 81],
       [40, 20, 66, 45, 44, 13, 20, 83,  4],
       [20, 78, 84, 11, 88,  8, 18, 52, 55],
       [34,  3, 45, 47, 91, 18, 63, 99, 36],
       [92, 68,  1, 75, 30, 45, 22, 50, 62],
       [55, 59, 92, 95, 46, 38, 54, 73, 65],
       [37, 33, 10, 84, 48, 55, 96, 13, 59],
       [58, 54, 31, 20,  6, 33, 85, 65,  5]])

In [136]:
ss>10

array([[ True,  True,  True,  True, False,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False]])

In [137]:
ss>50

array([[False,  True,  True,  True, False,  True, False, False, False],
       [ True, False, False,  True,  True, False, False, False,  True],
       [ True, False, False, False,  True,  True,  True,  True,  True],
       [False, False,  True, False, False, False, False,  True, False],
       [False,  True,  True, False,  True, False, False,  True,  True],
       [False, False, False, False,  True, False,  True,  True, False],
       [ True,  True, False,  True, False, False, False, False,  True],
       [ True,  True,  True,  True, False, False,  True,  True,  True],
       [False, False, False,  True, False,  True,  True, False,  True],
       [ True,  True, False, False, False, False,  True,  True, False]])

In [138]:
ss!=50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

### **max , **min , **average , **sum

In [142]:
x=np.random.randint(0,16,(4,3))
x

array([[13,  4, 12],
       [ 6,  2, 10],
       [14,  5, 10],
       [10,  1, 13]])

In [143]:
np.max(x,axis=0)

array([14,  5, 13])

In [145]:
np.max(x, axis=1)

array([13, 10, 14, 13])

In [146]:
x

array([[13,  4, 12],
       [ 6,  2, 10],
       [14,  5, 10],
       [10,  1, 13]])

In [147]:
np.min(x,axis=0)

array([ 6,  1, 10])

In [148]:
np.min(x,axis=1)

array([4, 2, 5, 1])

In [149]:
np.average(x)

8.333333333333334

In [150]:
np.average(x,axis=0)

array([10.75,  3.  , 11.25])

In [151]:
np.average(x,axis=1)

array([9.66666667, 6.        , 9.66666667, 8.        ])

In [152]:
np.sum(x)

100

In [153]:
np.sum(x,axis=0)

array([43, 12, 45])

In [154]:
np.sum(x,axis=1)

array([29, 18, 29, 24])

### sqrt, exp, log

In [156]:
array1=np.random.randint(1,15,(4,4))
array1

array([[11, 14, 12,  2],
       [ 1,  6,  1,  1],
       [10,  1,  8,  2],
       [ 1,  4, 10,  6]])

In [157]:
np.power(array1 ,3)

array([[1331, 2744, 1728,    8],
       [   1,  216,    1,    1],
       [1000,    1,  512,    8],
       [   1,   64, 1000,  216]], dtype=int32)

In [158]:
np.sqrt(array1)

array([[3.31662479, 3.74165739, 3.46410162, 1.41421356],
       [1.        , 2.44948974, 1.        , 1.        ],
       [3.16227766, 1.        , 2.82842712, 1.41421356],
       [1.        , 2.        , 3.16227766, 2.44948974]])

In [159]:
np.log(array1)

array([[2.39789527, 2.63905733, 2.48490665, 0.69314718],
       [0.        , 1.79175947, 0.        , 0.        ],
       [2.30258509, 0.        , 2.07944154, 0.69314718],
       [0.        , 1.38629436, 2.30258509, 1.79175947]])

In [160]:
np.exp(array1)

array([[5.98741417e+04, 1.20260428e+06, 1.62754791e+05, 7.38905610e+00],
       [2.71828183e+00, 4.03428793e+02, 2.71828183e+00, 2.71828183e+00],
       [2.20264658e+04, 2.71828183e+00, 2.98095799e+03, 7.38905610e+00],
       [2.71828183e+00, 5.45981500e+01, 2.20264658e+04, 4.03428793e+02]])

### sin, cos, tan

In [161]:
angels_arr = np.linspace(0, 360, 9).reshape(3, 3)
angels_arr

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [162]:
angels_arr = (angels_arr * 2 * np.pi) / 360
angels_arr

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

In [163]:
np.sin(angels_arr)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

In [164]:
np.cos(angels_arr)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

In [165]:
np.tan(angels_arr)

array([[ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16],
       [-1.00000000e+00, -1.22464680e-16,  1.00000000e+00],
       [ 5.44374645e+15, -1.00000000e+00, -2.44929360e-16]])

In [166]:
l=[True ,'3' , 4,0.5 ]
[type (item) for item in l]

[bool, str, int, float]

In [168]:
z=np.array([[1,2,3,4],[4,8,8,7]],dtype=float)
z

array([[1., 2., 3., 4.],
       [4., 8., 8., 7.]])

In [169]:
np.full((3,4),15)

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [175]:
np.empty(3)

array([10.75,  3.  , 11.25])

In [176]:
x3 = np.random.randint(10, size=(3, 4, 5)) 
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [177]:
x=np.array([[3, 5, 2, 4],
            [7, 6, 8, 8],
            [1, 6, 7, 7]])
x

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [178]:
#modefy_value
x[0,0]=5
x

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [179]:
x[::-1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [5, 5, 2, 4]])

In [182]:
print(x[::-2])
print(x[:,0])
print(x[0,:])

[[1 6 7 7]
 [5 5 2 4]]
[5 7 1]
[5 5 2 4]


In [184]:
x2_sub_copy = x[:2, :2].copy()
print(x2_sub_copy)

[[5 5]
 [7 6]]


### concatenate

In [186]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [187]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [191]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid,grid],axis=1))
print('-'*40)
print(np.concatenate([grid,grid]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
----------------------------------------
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


### vstack ,hstack

In [195]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [194]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### spliting

In [197]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [198]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [199]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [201]:
left, right = np.hsplit(grid, [2])
print(left)
print('-'*30)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [206]:
inches=np.random.randint(0,10)
np.sum((inches > 0.5) & (inches < 1)) 


0

In [207]:
X=np.random.randint(1,50,5)
np.sort(X, axis=0)

array([ 2, 11, 13, 24, 48])

In [208]:
X

array([ 2, 48, 11, 13, 24])

In [209]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [210]:
np.dtype({'names':('name', 'age', 'weight'),
 'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])